In [2]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import os
print(os.getcwd())

/content

In [4]:
os.chdir("/content/drive/My Drive/build_llm_from_scratch")

In [5]:
%pip install -q transformers torch pandas sentence-transformers

In [6]:
#imports
import json
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from sentence_transformers import SentenceTransformer,util

## Loading the model and tokenizer

for this experiment we will use google/flan-t5-base which is (~250M params)

In [7]:
MODEL_NAME = "google/flan-t5-base"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)
device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:122: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

### loading our Dataset

In [8]:
with open("hallucination_benchmark.json","r") as f:
    items=json.load(f)
print(f"{len(items)} questions found")

30 questions found

In [9]:
type(items)

list

In [10]:
items

[{'id': 1,
  'category': 'A',
  'context': None,
  'question': 'What is the capital of Australia?',
  'ground_truth': 'Canberra'},
 {'id': 2,
  'category': 'A',
  'context': None,
  'question': 'Who developed the theory of relativity?',
  'ground_truth': 'Albert Einstein'},
 {'id': 3,
  'category': 'A',
  'context': None,
  'question': 'What is the chemical symbol for gold?',
  'ground_truth': 'Au'},
 {'id': 4,
  'category': 'A',
  'context': None,
  'question': 'Which planet is known as the Red Planet?',
  'ground_truth': 'Mars'},
 {'id': 5,
  'category': 'A',
  'context': None,
  'question': 'In which year did World War II end?',
  'ground_truth': '1945'},
 {'id': 6,
  'category': 'A',
  'context': None,
  'question': 'What is the largest ocean on Earth?',
  'ground_truth': 'Pacific Ocean'},
 {'id': 7,
  'category': 'A',
  'context': None,
  'question': 'Who wrote Pride and Prejudice?',
  'ground_truth': 'Jane Austen'},
 {'id': 8,
  'category': 'A',
  'context': None,
  'question': 'What is the square root of 144?',
  'ground_truth': '12'},
 {'id': 9,
  'category': 'A',
  'context': None,
  'question': 'Which country was the first to successfully send a human into space?',
  'ground_truth': 'Soviet Union'},
 {'id': 10,
  'category': 'A',
  'context': None,
  'question': 'What is the longest river in Africa?',
  'ground_truth': 'Nile'},
 {'id': 11,
  'category': 'B',
  'context': None,
  'question': 'What is the capital of Bhutan?',
  'ground_truth': 'Thimphu'},
 {'id': 12,
  'category': 'B',
  'context': None,
  'question': 'Which scientist discovered the neutron?',
  'ground_truth': 'James Chadwick'},
 {'id': 13,
  'category': 'B',
  'context': None,
  'question': 'What is the tallest mountain in South America?',
  'ground_truth': 'Aconcagua'},
 {'id': 14,
  'category': 'B',
  'context': None,
  'question': 'Which country uses the currency called the Tugrik?',
  'ground_truth': 'Mongolia'},
 {'id': 15,
  'category': 'B',
  'context': None,
  'question': 'What is the deepest lake in the world?',
  'ground_truth': 'Lake Baikal'},
 {'id': 16,
  'category': 'C',
  'context': None,
  'question': 'Who was the U.S. president when humans first landed on the Moon?',
  'ground_truth': 'Richard Nixon'},
 {'id': 17,
  'category': 'C',
  'context': None,
  'question': 'What is the native country of the scientist who discovered penicillin?',
  'ground_truth': 'Scotland'},
 {'id': 18,
  'category': 'C',
  'context': None,
  'question': 'Which continent contains the country whose capital is Nairobi?',
  'ground_truth': 'Africa'},
 {'id': 19,
  'category': 'C',
  'context': None,
  'question': 'Which element has atomic number equal to the number of sides in a hexagon?',
  'ground_truth': 'Carbon'},
 {'id': 20,
  'category': 'C',
  'context': None,
  'question': 'What language is primarily spoken in the country where Machu Picchu is located?',
  'ground_truth': 'Spanish'},
 {'id': 21,
  'category': 'D',
  'context': 'Sarah bought 5 apples on Monday and 3 apples on Tuesday.',
  'question': 'How many apples did Sarah buy in total?',
  'ground_truth': '8'},
 {'id': 22,
  'category': 'D',
  'context': 'The meeting starts at 2 PM and lasts for 90 minutes.',
  'question': 'When does the meeting end?',
  'ground_truth': '3:30 PM'},
 {'id': 23,
  'category': 'D',
  'context': 'John is older than Mary. Mary is older than Tom.',
  'question': 'Who is the youngest?',
  'ground_truth': 'Tom'},
 {'id': 24,
  'category': 'D',
  'context': 'A train travels 60 km in 1 hour.',
  'question': 'How far will it travel in 3 hours at the same speed?',
  'ground_truth': '180 km'},
 {'id': 25,
  'category': 'D',
  'context': 'The blue box contains a key. The red box contains a book.',
  'question': 'Which box contains the key?',
  'ground_truth': 'Blue box'},
 {'id': 26,
  'category': 'E',
  'context': None,
  'question': 'Who won the Nobel Prize in Physics in 2035?',
  'ground_truth': 'Unknown / has not happened'},
 {'id': 27,
  'category': 'E',
  'context': None,
  'question': 'What is the capital city of the country Zoravia?',
  'ground_truth': 'No such recognized country'},
 {'id': 28,
  'category': 'E',
  'context': None,
  'question': 'Which scientist invented the Quantum Bicycle?',
  'ground_truth': 'No known scientist; fictional concept'},
 {'id': 29,
  'category': 'E',
  'context': None,
  'question': 'What are the main exports of the Republic of Eldoria?',
  'ground_truth': 'Eldoria is fictional'},
 {'id': 30,
  'category': 'E',
  'context': None,
  'question': 'What is the population of Mars City in 2024?',
  'ground_truth': 'No established Mars City exists'}]

### Building the prompt

In [11]:
def build_prompt(item):
    if item["context"]:
        return f' Context : {item["context"]}\nQuestion: {item["question"]}\nAnswer : '
    return f'Question : {item["question"]}\nAnswer : '

In [12]:
def generate_answer(prompt, max_new_tokens=32):
    inputs=tokenizer(prompt,return_tensors="pt")
    #do_sample=False makes generation deterministic
    outputs=model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False, num_beams=1)
    return tokenizer.decode(outputs[0],skip_special_tokens=True)

In [13]:
results = []
for item in items:
    prompt = build_prompt(item)
    answer = generate_answer(prompt)
    results.append({
        "id": item["id"],
        "category": item["category"],
        "question": item["question"],
        "ground_truth": item["ground_truth"],
        "model_output": answer,   
    })
    print(item["id"], "->", answer)

1 -> melbourne
2 -> john d roosevelt
3 -> g
4 -> uranus
5 -> 1945
6 -> pacific ocean
7 -> edward edward scott
8 -> 144
9 -> russia
10 -> rhine
11 -> chengdu
12 -> charles edward scott
13 -> sao paulo
14 -> ukraine
15 -> lake baikal
16 -> john f kennedy
17 -> sweden
18 -> africa
19 -> tin
20 -> Spanish Language
21 -> 5
22 -> 2 PM
23 -> Mary
24 -> 60 km / 1 hour = 20 km / hour. 3 hours = 3 hours * 60 km / hour = 480 km / hour.
25 -> blue
26 -> edward roosevelt
27 -> zoravia
28 -> john d. salinger
29 -> sugar
30 -> 87,020

### similarity check

we will be using another model "all-MiniLM-L6-v2" to caculate the similarity score that will calculate the similarity between ground truth and predicted answer

In [14]:
sim_model= SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [15]:
for r in results:
    emb_output = sim_model.encode(r["model_output"], convert_to_tensor=True)
    emb_truth = sim_model.encode(r["ground_truth"], convert_to_tensor=True)
    r["similarity_score"] = round(util.cos_sim(emb_output, emb_truth).item(), 3)
    r["fabrication"] = ""  # still fill this by hand — see note below

### Saving the results in csv

In [16]:
df = pd.DataFrame(results)
df.to_csv("results.csv", index=False)
df.sort_values("similarity_score")

,id,category,question,ground_truth,model_output,similarity_score,fabrication
29,30,E,What is the population of Mars City in 2024?,No established Mars City exists,"87,020",-0.069,
28,29,E,What are the main exports of the Republic of E...,Eldoria is fictional,sugar,-0.026,
26,27,E,What is the capital city of the country Zoravia?,No such recognized country,zoravia,0.101,
25,26,E,Who won the Nobel Prize in Physics in 2035?,Unknown / has not happened,edward roosevelt,0.102,
2,3,A,What is the chemical symbol for gold?,Au,g,0.250,
10,11,B,What is the capital of Bhutan?,Thimphu,chengdu,0.257,
9,10,A,What is the longest river in Africa?,Nile,rhine,0.311,
6,7,A,Who wrote Pride and Prejudice?,Jane Austen,edward edward scott,0.321,
12,13,B,What is the tallest mountain in South America?,Aconcagua,sao paulo,0.330,
18,19,C,Which element has atomic number equal to the n...,Carbon,tin,0.345,
27,28,E,Which scientist invented the Quantum Bicycle?,No known scientist; fictional concept,john d. salinger,0.354,
11,12,B,Which scientist discovered the neutron?,James Chadwick,charles edward scott,0.379,
1,2,A,Who developed the theory of relativity?,Albert Einstein,john d roosevelt,0.402,
22,23,D,Who is the youngest?,Tom,Mary,0.443,
23,24,D,How far will it travel in 3 hours at the same ...,180 km,60 km / 1 hour = 20 km / hour. 3 hours = 3 hou...,0.444,
3,4,A,Which planet is known as the Red Planet?,Mars,uranus,0.513,
13,14,B,Which country uses the currency called the Tug...,Mongolia,ukraine,0.539,
15,16,C,Who was the U.S. president when humans first l...,Richard Nixon,john f kennedy,0.589,
24,25,D,Which box contains the key?,Blue box,blue,0.658,
16,17,C,What is the native country of the scientist wh...,Scotland,sweden,0.669,
7,8,A,What is the square root of 144?,12,144,0.688,
0,1,A,What is the capital of Australia?,Canberra,melbourne,0.722,
8,9,A,Which country was the first to successfully se...,Soviet Union,russia,0.741,
20,21,D,How many apples did Sarah buy in total?,8,5,0.743,
21,22,D,When does the meeting end?,3:30 PM,2 PM,0.761,
19,20,C,What language is primarily spoken in the count...,Spanish,Spanish Language,0.902,
5,6,A,What is the largest ocean on Earth?,Pacific Ocean,pacific ocean,1.000,
4,5,A,In which year did World War II end?,1945,1945,1.000,
14,15,B,What is the deepest lake in the world?,Lake Baikal,lake baikal,1.000,
17,18,C,Which continent contains the country whose cap...,Africa,africa,1.000,

### updating the df (manually filled the fabriction column)

In [17]:
df= pd.read_csv("results_with_fabrications.csv")
df.head()

,id,category,question,ground_truth,model_output,similarity_score,fabrication
0,1,A,What is the capital of Australia?,Canberra,melbourne,0.722,NO
1,2,A,Who developed the theory of relativity?,Albert Einstein,john d roosevelt,0.402,YES
2,3,A,What is the chemical symbol for gold?,Au,g,0.250,YES
3,4,A,Which planet is known as the Red Planet?,Mars,uranus,0.513,NO
4,5,A,In which year did World War II end?,1945,1945,1.000,NO

In [19]:
df

,id,category,question,ground_truth,model_output,similarity_score,fabrication
0,1,A,What is the capital of Australia?,Canberra,melbourne,0.722,NO
1,2,A,Who developed the theory of relativity?,Albert Einstein,john d roosevelt,0.402,YES
2,3,A,What is the chemical symbol for gold?,Au,g,0.250,YES
3,4,A,Which planet is known as the Red Planet?,Mars,uranus,0.513,NO
4,5,A,In which year did World War II end?,1945,1945,1.000,NO
5,6,A,What is the largest ocean on Earth?,Pacific Ocean,pacific ocean,1.000,NO
6,7,A,Who wrote Pride and Prejudice?,Jane Austen,edward edward scott,0.321,NO
7,8,A,What is the square root of 144?,12,144,0.688,NO
8,9,A,Which country was the first to successfully se...,Soviet Union,russia,0.741,NO
9,10,A,What is the longest river in Africa?,Nile,rhine,0.311,NO
10,11,B,What is the capital of Bhutan?,Thimphu,chengdu,0.257,NO
11,12,B,Which scientist discovered the neutron?,James Chadwick,charles edward scott,0.379,YES
12,13,B,What is the tallest mountain in South America?,Aconcagua,sao paulo,0.330,NO
13,14,B,Which country uses the currency called the Tug...,Mongolia,ukraine,0.539,NO
14,15,B,What is the deepest lake in the world?,Lake Baikal,lake baikal,1.000,NO
15,16,C,Who was the U.S. president when humans first l...,Richard Nixon,john f kennedy,0.589,NO
16,17,C,What is the native country of the scientist wh...,Scotland,sweden,0.669,NO
17,18,C,Which continent contains the country whose cap...,Africa,africa,1.000,NO
18,19,C,Which element has atomic number equal to the n...,Carbon,tin,0.345,NO
19,20,C,What language is primarily spoken in the count...,Spanish,Spanish Language,0.902,NO
20,21,D,How many apples did Sarah buy in total?,8,5,0.743,NO
21,22,D,When does the meeting end?,3:30 PM,2:00 PM,0.761,NO
22,23,D,Who is the youngest?,Tom,Mary,0.443,NO
23,24,D,How far will it travel in 3 hours at the same ...,180 km,60 km / 1 hour = 20 km / hour. 3 hours = 3 hou...,0.444,NO
24,25,D,Which box contains the key?,Blue box,blue,0.658,NO
25,26,E,Who won the Nobel Prize in Physics in 2035?,Unknown / has not happened,edward roosevelt,0.102,YES
26,27,E,What is the capital city of the country Zoravia?,No such recognized country,zoravia,0.101,YES
27,28,E,Which scientist invented the Quantum Bicycle?,No known scientist; fictional concept,john d. salinger,0.354,YES
28,29,E,What are the main exports of the Republic of E...,Eldoria is fictional,sugar,-0.026,YES
29,30,E,What is the population of Mars City in 2024?,No established Mars City exists,"87,020",-0.069,YES

In [20]:
total_questions = len(df)

# Fabrications / hallucinations
hallucinations = (df["fabrication"]=="YES").sum()
# Hallucination rate
hallucination_rate = (hallucinations/total_questions)*100
# Average similarity
avg_similarity = df["similarity_score"].mean()

print("      Evaluation Results    ")
print(f"Total Questions: {total_questions}")
print(f"Fabrications: {hallucinations}")
print(f"Fabrications Rate: {hallucination_rate:.2f}%")
print(f"Average Similarity Score: {avg_similarity:.3f}")

      Evaluation Results
Total Questions: 30
Fabrications: 8
Fabrications Rate: 26.67%
Average Similarity Score: 0.516